# Generated by Django 2.2.3 on 2019-07-23 12:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('eventsmanager', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='finish_date',
            new_name='eventDeadline',
        ),
        migrations.AddField(
            model_name='event',
            name='eventInitialDate',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='PrivateGoal',
            fields=[
                ('goalId', models.AutoField(primary_key=True, serialize=False)),
                ('goalName', models.CharField(max_length=100)),
                ('goalInitialDate', models.DateTimeField()),
                ('goalDeadline', models.DateTimeField()),
                ('userId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='event',
            name='goalId',
            field=models.ForeignKey(default=0, on_delete=django.db.models.deletion.CASCADE, to='eventsmanager.PrivateGoal'),
            preserve_default=False,
        ),
    ]
