# Generated by Django 2.2.3 on 2019-07-29 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eventsmanager', '0002_auto_20190723_1225'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='goalId',
            new_name='eventGoalId',
        ),
    ]
